# Uncomment this line to define a global platform for your project

target ‘Weather‘ do

    use_frameworks!
    pod 'Alamofire'
    pod 'KRProgressHUD'
    pod 'ObjectMapper'
    pod 'SDWebImage'
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
    
    pod 'RxSwift'
    pod 'RxCocoa'

end



